title: FaTiH3446.github.io
description: >
  This website is created as part of my Computer Science Principles course.
  It showcases my projects, assignments, and explorations in computing.


theme: jekyll-theme-minimal


nav:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Projects
    url: /project
  - name: Big Idea
    url: /bigideas
  - name: Documentation
    url: /documentation
<ul class="menu">
  {% for item in site.nav %}
    <li><a href="{{ item.url | relative_url }}">{{ item.name }}</a></li>
  {% endfor %}
  <li><a href="/project-v3/">Project V3</a></li>
</ul>
